### ISSUE TITLE
This action should be triggered and receive inputs via workflow_dispatch

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/action-create-release-pr#3]
We should follow the example of [MetaMask/action-monorepo-release-pr](https://github.com/MetaMask/action-monorepo-release-pr).

```yaml
on:
    workflow_dispatch:
        inputs:
            release-type:
                description: 'A SemVer version diff, i.e. major, minor, patch, prerelease etc. Mutually exclusive with "release-version".'
                required: false
            release-version:
                description: 'A specific version to bump to. Mutually exclusive with "release-type".'
                required: false
```
